version: "2.1"

services: 
    logstash: 
        build:
            context: ./logstash
            dockerfile: Dockerfile
        volumes: 
            - ${PWD}/logstash/pcap:/usr/share/logstash/pcap
        networks: 
            - tap

volumes:
    pcap: 

networks:
    tap:
        name: tap
        driver: bridge
