version: "2.1"

services: 
    logstash: 
        build:
            context: ./logstash
            dockerfile: Dockerfile
        volumes: 
            - ${PWD}/logstash/pcap:/usr/share/logstash/pcap
        networks: 
            - tap
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        ports:
            - 9200:9200
            - 9300:9300
        environment: 
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
        networks: 
            tap:
                ipv4_address: 10.0.100.51
    kibana:
        build:
            context: ./kibana
            dockerfile: Dockerfile
        ports:
            - 5601:5601
        depends_on: 
            - elasticsearch
        networks: 
            tap:
                ipv4_address: 10.0.100.52


volumes:
    pcap: 

networks:
    tap:
        name: tap
        driver: bridge
